# Generated by Django 3.1.7 on 2021-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.IntegerField(null=True)),
                ('act_fname', models.CharField(max_length=20)),
                ('act_lname', models.CharField(max_length=20)),
                ('act_gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_id', models.IntegerField(null=True)),
                ('dir_fname', models.CharField(max_length=20)),
                ('dir_lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_id', models.IntegerField(null=True)),
                ('mov_name', models.CharField(max_length=20)),
                ('mov_year', models.IntegerField(null=True)),
                ('mov_dt_rel', models.DateField(null=True)),
                ('mov_rel_country', models.CharField(max_length=20)),
                ('mov_time', models.IntegerField(null=True)),
            ],
        ),
    ]
